### ISSUE TITLE
Windows install problem

### ISSUE THREAD

**Issue by Green7** [moul/protoc-gen-gotemplate#107]
It is not possible to install protoc-gen-gotemplate under Windows.

go get github.com/moul/protoc-gen-gotemplate does not work because directory "examples/single-package-mode/templates/{{.File.Name|dir}}" has forbidden character ('|') in the name.

**Comment by moul** [comment]
Hi @Green7, you should now be able to install it on windows with go1.11, can you give a new try?

**Comment by moul** [comment]
Closing now, feel free to reopen if needed
