### ISSUE TITLE
Regex functions in template not working

### ISSUE THREAD

**Issue by gigimushroom** [moul/protoc-gen-gotemplate#80]
regex functions defined in:
http://masterminds.github.io/sprig/strings.html
all not working.

function "regexFindAll" not defined

Any ideas?

**Comment by moul** [comment]
Hi @gigimushroom, thank you for your feedback

The sprig dependency was outdated; #81 bumps it to the correct version + add a working example

**Comment by gigimushroom** [comment]
Thank you
