### ISSUE TITLE
Messages types from imported proto files

### ISSUE THREAD

**Issue by bruth** [moul/protoc-gen-gotemplate#92]
Hi! I have the following `service.proto` file that imports from another proto file:

```protobuf
syntax = "proto3";
package main;

option go_package = "main";

import "iam/v1/authn.proto";

service Service {
  rpc Authenticate (arcus.apis.iam.v1.AuthenticateRequest) returns (arcus.apis.iam.v1.AuthenticateReply);
}
```

I've validated the import paths are correct because I can generate gRPC code for this service properly.

I found the [import example](https://github.com/moul/protoc-gen-gotemplate/blob/master/examples/import/templates/output.go.tmpl) and tried it with my service, but the method is not written out. It appears the `with $t := $m.InputType | getMessageType $.File` returns nil so the block exits. Any idea to why this is failing to get the message type?

**Comment by weitzj** [comment]
You could try some of the plugin options - this is just a wild guess

```
--gotemplate_out=single-package-mode=true,debug=true,all=true
```

**Comment by bruth** [comment]
@weitzj Thanks! That led me in the right direction. I found the [single-package-mode example](https://github.com/moul/protoc-gen-gotemplate/blob/master/examples/single-package-mode/templates/%7B%7B.File.Name%7Cdir%7D%7D/service.go.tmpl) which is close to what I want.

I am now having a separate issue with the `GoPackage` struct not respecting the package alias in the `go_package` proto option, e.g. `option go_package = "github.com/acus/apis/iam/v1;iam";` which gRPC generated code appears to handle.

**Comment by weitzj** [comment]
Maybe this helps:

```
    {{- $dependencyProtoFile := . | getProtoFile -}}
    {{- $pathToImport := regexSplit ";" $dependencyProtoFile.Options.GoPackage -1 | first -}}
```

**Comment by bruth** [comment]
I appreciate it, thank you. I was trying a similar approach..

```
  {{- $path := $dependency.GoPkg.Path | splitList ";" | first}}
  {{- $alias := $dependency.GoPkg.Path | splitList ";" | last}}
```

**Comment by bruth** [comment]
After a bit of trial and error, the following template is working:

```
// File generated with protoc-gen-gotemplate.
// DO NOT EDIT.
package {{.File.Package}}

{{- $file := .File}}
{{- $currentFile := $file.Name | getProtoFile}}

import (
  "golang.org/x/net/context"

  {{- range .File.Dependency}}
    {{- $dependency := . | getProtoFile}}
    {{- $path := $dependency.GoPkg.Path | splitList ";" | first}}
    {{- $alias := $dependency.GoPkg.Path | splitList ";" | last}}
  {{$alias}} "{{$path}}"
  {{- end}}
)

type Service interface {
{{- range .Service.Method}}
{{- $in := .InputType | getMessageType $file}}
{{- $inType := regexSplit ";" ($in.GoType $currentFile.GoPkg.Path) -1 | last}}

{{- $out := .OutputType | getMessageType $file}}
{{- $outType := regexSplit ";" ($out.GoType $currentFile.GoPkg.Path) -1 | last}}
  {{.Name}}(context.Context, *{{- $inType}}) (*{{- $outType}}, error)
{{- end}}
}
```

Given this protobuf file (which intentionally imports a couple arbitrary things.. including a duplicate package name)..

```
syntax = "proto3";
package main;

import "iam/v1/authn.proto";
import "iam/v1/authz.proto";
import "cas/v1/messages.proto";

service Service {
  rpc Authenticate (arcus.apis.iam.v1.AuthenticateRequest) returns (arcus.apis.iam.v1.AuthenticateReply);
  rpc Authorize (arcus.apis.iam.v1.AuthorizeRequest) returns (arcus.apis.iam.v1.AuthorizeReply);
  rpc Put (arcus.apis.cas.v1.PutRequest) returns (arcus.apis.cas.v1.PutReply);
}
```

Will result in the following after `goimports -w` to remove redundant imports and format.

```go
// File generated with protoc-gen-gotemplate.
// DO NOT EDIT.
package main

import (
	cas "github.com/arcus/apis/cas/v1"
	iam "github.com/arcus/apis/iam/v1"
	"golang.org/x/net/context"
)

type Service interface {
	Authenticate(context.Context, *iam.AuthenticateRequest) (*iam.AuthenticateReply, error)
	Authorize(context.Context, *iam.AuthorizeRequest) (*iam.AuthorizeReply, error)
	Put(context.Context, *cas.PutRequest) (*cas.PutReply, error)
}
```

**Comment by weitzj** [comment]
Looks like we eventually ended up with the same approach: running `goimports` to cleanup duplicate imports. :)

So.Probably the issue can be closed, correct?

**Comment by bruth** [comment]
Yes definitely. I appreciate the help.
